[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/tmp/supervisord-agent.pid

[unix_http_server]
file=/tmp/supervisor-agent.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor-agent.sock

[program:agent]
command=taskiq worker --workers 1 --max-async-tasks 10 app.queue.brokers:broker_agent app.queue.tasks.agent_run --ack-type when_executed
stopasgroup=true
killasgroup=true
autorestart=unexpected
startretries=3
exitcodes=0
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[eventlistener:fail_fast]
command=python /app/supervisord/fail_fast.py
events=PROCESS_STATE_FATAL
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
