[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/tmp/supervisord-insights.pid

[unix_http_server]
file=/tmp/supervisor-insights.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor-insights.sock

[program:digest]
command=taskiq worker app.brokers:broker_digest app.insights.snapshot.tasks.snapshot --ack-type when_executed
stopasgroup=true
killasgroup=true
autorestart=unexpected
startretries=3
exitcodes=0
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:briefing]
command=taskiq worker app.brokers:broker_briefing app.insights.briefing.tasks.briefing --ack-type when_executed
stopasgroup=true
killasgroup=true
autorestart=unexpected
startretries=3
exitcodes=0
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[eventlistener:fail_fast]
command=python /app/supervisord/fail_fast.py
events=PROCESS_STATE_FATAL
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
