[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/tmp/supervisord-scheduler.pid

[unix_http_server]
file=/tmp/supervisor-scheduler.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor-scheduler.sock

[program:sched-meta]
command=taskiq scheduler app.queue.schedulers:scheduler_metadata app.queue.registry
stopasgroup=true
killasgroup=true
autorestart=unexpected
startretries=3
exitcodes=0
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:sched-digest]
command=taskiq scheduler app.queue.schedulers:scheduler_digest app.queue.registry
stopasgroup=true
killasgroup=true
autorestart=unexpected
startretries=3
exitcodes=0
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:sched-briefing]
command=taskiq scheduler app.queue.schedulers:scheduler_briefing app.queue.registry
stopasgroup=true
killasgroup=true
autorestart=unexpected
startretries=3
exitcodes=0
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[eventlistener:fail_fast]
command=python /app/supervisord/fail_fast.py
events=PROCESS_STATE_FATAL
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
