/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keywords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Keywords */
        get: operations["list_keywords_api_v1_keywords_get"];
        put?: never;
        /** Create Keyword */
        post: operations["create_keyword_api_v1_keywords_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keywords/{keyword_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Keyword */
        delete: operations["delete_keyword_api_v1_keywords__keyword_id__delete"];
        options?: never;
        head?: never;
        /** Update Keyword */
        patch: operations["update_keyword_api_v1_keywords__keyword_id__patch"];
        trace?: never;
    };
    "/api/v1/me/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Subscriptions */
        get: operations["list_subscriptions_api_v1_me_subscriptions_get"];
        put?: never;
        /** Create Subscription */
        post: operations["create_subscription_api_v1_me_subscriptions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/subscriptions/{keyword_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Subscription */
        delete: operations["delete_subscription_api_v1_me_subscriptions__keyword_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Watchlist */
        get: operations["list_watchlist_api_v1_me_watchlist_get"];
        put?: never;
        /** Add To Watchlist */
        post: operations["add_to_watchlist_api_v1_me_watchlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/watchlist/{news_article_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove From Watchlist */
        delete: operations["remove_from_watchlist_api_v1_me_watchlist__news_article_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List News */
        get: operations["list_news_api_v1_news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news/{news_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get News */
        get: operations["get_news_api_v1_news__news_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news/fetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fetch News */
        post: operations["fetch_news_api_v1_news_fetch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisResponse
         * @description AI analysis result embedded in NewsResponse.
         */
        AnalysisResponse: {
            /** Titleja */
            titleJa: string;
            /** Summaryja */
            summaryJa: string;
            /** Sentiment */
            sentiment: string;
            /** Impactscore */
            impactScore: number;
            /** Keytopics */
            keyTopics?: string[] | null;
            /** Reasoning */
            reasoning?: string | null;
            /** Aiprovider */
            aiProvider: string;
            /**
             * Analyzedat
             * Format: date-time
             */
            analyzedAt: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * KeywordBrief
         * @description Minimal keyword info embedded in NewsResponse.
         */
        KeywordBrief: {
            /** Id */
            id: number;
            /** Keyword */
            keyword: string;
            /** Category */
            category: string;
        };
        /**
         * KeywordCreate
         * @description POST /api/v1/keywords request body.
         */
        KeywordCreate: {
            /** Keyword */
            keyword: string;
            /**
             * Category
             * @default custom
             */
            category: string;
        };
        /**
         * KeywordListResponse
         * @description GET /api/v1/keywords response wrapper.
         */
        KeywordListResponse: {
            /** Items */
            items: components["schemas"]["KeywordResponse"][];
        };
        /**
         * KeywordResponse
         * @description Keyword in API responses (list, detail, embedded in news).
         */
        KeywordResponse: {
            /** Id */
            id: number;
            /** Keyword */
            keyword: string;
            /** Category */
            category: string;
            /** Isactive */
            isActive: boolean;
            /**
             * Articlecount
             * @default 0
             */
            articleCount: number;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /**
         * KeywordUpdate
         * @description PATCH /api/v1/keywords/{id} request body.
         */
        KeywordUpdate: {
            /** Isactive */
            isActive?: boolean | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * NewsFetchRequest
         * @description POST /api/v1/news/fetch request body.
         */
        NewsFetchRequest: {
            /** Keywordids */
            keywordIds?: number[] | null;
        };
        /**
         * NewsFetchResponse
         * @description POST /api/v1/news/fetch response.
         */
        NewsFetchResponse: {
            /** Message */
            message: string;
            /** Keywordscount */
            keywordsCount: number;
            /** Jobid */
            jobId: string;
        };
        /**
         * NewsResponse
         * @description Single news article with analysis and keywords.
         */
        NewsResponse: {
            /** Id */
            id: number;
            /** Titleoriginal */
            titleOriginal: string;
            /** Url */
            url: string;
            /** Source */
            source: string;
            /** Publishedat */
            publishedAt?: string | null;
            /**
             * Fetchedat
             * Format: date-time
             */
            fetchedAt: string;
            /** Content */
            content?: string | null;
            /** Contentfetchedat */
            contentFetchedAt?: string | null;
            /**
             * Keywords
             * @default []
             */
            keywords: components["schemas"]["KeywordBrief"][];
            analysis?: components["schemas"]["AnalysisResponse"] | null;
            /**
             * Iswatched
             * @default false
             */
            isWatched: boolean;
        };
        /**
         * PaginatedNewsResponse
         * @description Paginated list of news articles.
         */
        PaginatedNewsResponse: {
            /** Items */
            items: components["schemas"]["NewsResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Perpage */
            perPage: number;
            /** Totalpages */
            totalPages: number;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refreshtoken */
            refreshToken: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Displayname */
            displayName?: string | null;
        };
        /**
         * SubscriptionCreate
         * @description POST /api/v1/me/subscriptions request body.
         */
        SubscriptionCreate: {
            /** Keywordid */
            keywordId: number;
        };
        /**
         * SubscriptionListResponse
         * @description GET /api/v1/me/subscriptions response wrapper.
         */
        SubscriptionListResponse: {
            /** Items */
            items: components["schemas"]["SubscriptionResponse"][];
        };
        /**
         * SubscriptionResponse
         * @description Subscription in API responses.
         */
        SubscriptionResponse: {
            /** Id */
            id: number;
            /** Keywordid */
            keywordId: number;
            /** Keyword */
            keyword: string;
            /** Category */
            category: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Accesstoken */
            accessToken: string;
            /** Refreshtoken */
            refreshToken: string;
            /**
             * Tokentype
             * @default bearer
             */
            tokenType: string;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Displayname */
            displayName: string | null;
            /** Isactive */
            isActive: boolean;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WatchlistCreate
         * @description POST /api/v1/me/watchlist request body.
         */
        WatchlistCreate: {
            /** Newsarticleid */
            newsArticleId: number;
        };
        /**
         * WatchlistListResponse
         * @description GET /api/v1/me/watchlist response wrapper.
         */
        WatchlistListResponse: {
            /** Items */
            items: components["schemas"]["WatchlistResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Perpage */
            perPage: number;
            /** Totalpages */
            totalPages: number;
        };
        /**
         * WatchlistResponse
         * @description Watchlist item in API responses.
         */
        WatchlistResponse: {
            /** Id */
            id: number;
            /** Newsarticleid */
            newsArticleId: number;
            /** Titleoriginal */
            titleOriginal: string;
            /** Url */
            url: string;
            /** Source */
            source: string;
            /** Publishedat */
            publishedAt?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_keywords_api_v1_keywords_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeywordListResponse"];
                };
            };
        };
    };
    create_keyword_api_v1_keywords_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeywordCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeywordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_keyword_api_v1_keywords__keyword_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyword_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_keyword_api_v1_keywords__keyword_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyword_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeywordUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeywordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_subscriptions_api_v1_me_subscriptions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionListResponse"];
                };
            };
        };
    };
    create_subscription_api_v1_me_subscriptions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_subscription_api_v1_me_subscriptions__keyword_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyword_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_watchlist_api_v1_me_watchlist_get: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_to_watchlist_api_v1_me_watchlist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_from_watchlist_api_v1_me_watchlist__news_article_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                news_article_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_news_api_v1_news_get: {
        parameters: {
            query?: {
                keywordId?: number | null;
                myKeywords?: boolean;
                sentiment?: string | null;
                minImpact?: number | null;
                sortBy?: string;
                sortOrder?: string;
                page?: number;
                perPage?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedNewsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_news_api_v1_news__news_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                news_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fetch_news_api_v1_news_fetch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["NewsFetchRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsFetchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
