/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Categories
         * @description List all categories with nested keywords and article counts.
         */
        get: operations["list_categories_api_v1_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keywords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Keywords */
        get: operations["list_keywords_api_v1_keywords_get"];
        put?: never;
        /** Create Keyword */
        post: operations["create_keyword_api_v1_keywords_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keywords/{keyword_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Keyword */
        delete: operations["delete_keyword_api_v1_keywords__keyword_id__delete"];
        options?: never;
        head?: never;
        /** Update Keyword */
        patch: operations["update_keyword_api_v1_keywords__keyword_id__patch"];
        trace?: never;
    };
    "/api/v1/me/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Watchlist */
        get: operations["list_watchlist_api_v1_me_watchlist_get"];
        put?: never;
        /** Add To Watchlist */
        post: operations["add_to_watchlist_api_v1_me_watchlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/watchlist/{news_article_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove From Watchlist */
        delete: operations["remove_from_watchlist_api_v1_me_watchlist__news_article_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List News */
        get: operations["list_news_api_v1_news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news/embed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Backfill embeddings for analyses that are missing them
         * @description Generate vector embeddings for all analyses where embedding IS NULL.
         *
         *     Requires authentication to prevent unintended Gemini API cost.
         */
        post: operations["embed_news_api_v1_news_embed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news/{news_id}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find semantically similar articles using pgvector cosine distance
         * @description Return articles most similar to the given article, ordered by cosine distance.
         *
         *     Returns an empty list (not 404) if the article has no embedding yet.
         */
        get: operations["get_similar_news_api_v1_news__news_id__similar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news/{news_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get News */
        get: operations["get_news_api_v1_news__news_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news/fetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fetch News
         * @description Enqueue a news fetch task. Returns immediately with a task ID.
         */
        post: operations["fetch_news_api_v1_news_fetch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sources
         * @description List all news sources.
         */
        get: operations["list_sources_api_v1_sources_get"];
        put?: never;
        /**
         * Create Source
         * @description Create a new news source.
         */
        post: operations["create_source_api_v1_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Source
         * @description Get a single news source by ID.
         */
        get: operations["get_source_api_v1_sources__source_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Source
         * @description Delete a news source.
         */
        delete: operations["delete_source_api_v1_sources__source_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Toggle Source
         * @description Toggle a news source's is_active status.
         */
        patch: operations["toggle_source_api_v1_sources__source_id__toggle_patch"];
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CategoryDetail
         * @description Enriched category with articleCount and nested keywords.
         */
        CategoryDetail: {
            /** Id */
            id: number;
            slug: components["schemas"]["CategorySlug"];
            name: components["schemas"]["CategoryName"];
            /**
             * Articlecount
             * @default 0
             */
            articleCount: number;
            /**
             * Keywords
             * @default []
             */
            keywords: components["schemas"]["KeywordStatEmbed"][];
        };
        /**
         * CategoryDetailList
         * @description Wrapper for enriched category list endpoint.
         */
        CategoryDetailList: {
            /** Items */
            items: components["schemas"]["CategoryDetail"][];
        };
        /**
         * CategoryEmbed
         * @description カテゴリの基本参照情報（slug + 名前）
         */
        CategoryEmbed: {
            slug: components["schemas"]["CategorySlug"];
            name: components["schemas"]["CategoryName"];
        };
        /**
         * CategoryName
         * @description Japanese display name for a category.
         *
         *     Invariants:
         *     - Contains word characters, middle dot (・), spaces, or hyphens
         *     - Not empty or whitespace-only
         *     - 1-50 characters
         *     - Immutable after creation
         */
        CategoryName: string;
        /**
         * CategorySlug
         * @description URL-safe category identifier.
         *
         *     Invariants:
         *     - Starts with lowercase letter or digit
         *     - Contains only lowercase letters, digits, and underscores
         *     - 1-50 characters
         *     - Immutable after creation
         */
        CategorySlug: string;
        /**
         * EmbedResponse
         * @description POST /api/v1/news/embed response.
         */
        EmbedResponse: {
            /** Message */
            message: string;
            /** Embeddedcount */
            embeddedCount: number;
            /** Skippedcount */
            skippedCount: number;
            /** Errorcount */
            errorCount: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImpactLevel
         * @enum {string}
         */
        ImpactLevel: "low" | "medium" | "high" | "critical";
        /**
         * KeywordCreate
         * @description POST /api/v1/keywords request body.
         */
        KeywordCreate: {
            /** @description Keyword tag name (1-100 chars) */
            name: components["schemas"]["KeywordName"];
            /** Categoryid */
            categoryId: number;
        };
        /**
         * KeywordDetail
         * @description Keyword in API responses (list, detail).
         */
        KeywordDetail: {
            /** Id */
            id: number;
            name: components["schemas"]["KeywordName"];
            category: components["schemas"]["CategoryEmbed"];
            status: components["schemas"]["KeywordStatus"];
            /**
             * Articlecount
             * @default 0
             */
            articleCount: number;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /**
         * KeywordDetailList
         * @description GET /api/v1/keywords wrapper.
         */
        KeywordDetailList: {
            /** Items */
            items: components["schemas"]["KeywordDetail"][];
        };
        /**
         * KeywordEmbed
         * @description キーワードタグ（ニュース埋め込み用）
         */
        KeywordEmbed: {
            /** Id */
            id: number;
            name: components["schemas"]["KeywordName"];
        };
        /**
         * KeywordName
         * @description Tag name for a technology or theme within a sector.
         *
         *     Invariants:
         *     - Contains at least one word character (\w)
         *     - Only word chars (Unicode), spaces, hyphens, dots, &, /, +, #
         *     - 1-100 characters after trimming
         *     - Immutable after creation
         */
        KeywordName: string;
        /**
         * KeywordStatEmbed
         * @description キーワード＋記事数（カテゴリ内集計表示用）
         */
        KeywordStatEmbed: {
            /** Id */
            id: number;
            name: components["schemas"]["KeywordName"];
            /**
             * Articlecount
             * @default 0
             */
            articleCount: number;
        };
        /**
         * KeywordStatus
         * @enum {string}
         */
        KeywordStatus: "provisional" | "official" | "blacklisted";
        /**
         * KeywordUpdate
         * @description PATCH /api/v1/keywords/{id} request body.
         */
        KeywordUpdate: {
            /** Categoryid */
            categoryId?: number | null;
        };
        /**
         * NewsBrief
         * @description GET /api/v1/news — 一覧カード用
         */
        NewsBrief: {
            /** Id */
            id: number;
            /** Translatedtitle */
            translatedTitle: string;
            /** Summary */
            summary: string;
            impactLevel: components["schemas"]["ImpactLevel"];
            sourceName: components["schemas"]["SourceName"];
            /** Publishedat */
            publishedAt?: string | null;
            /**
             * Keywords
             * @default []
             */
            keywords: components["schemas"]["KeywordEmbed"][];
            /**
             * Iswatched
             * @default false
             */
            isWatched: boolean;
        };
        /**
         * NewsDetail
         * @description GET /api/v1/news/{id} — 詳細画面用
         */
        NewsDetail: {
            /** Id */
            id: number;
            /** Translatedtitle */
            translatedTitle: string;
            /** Summary */
            summary: string;
            impactLevel: components["schemas"]["ImpactLevel"];
            /** Reasoning */
            reasoning: string;
            /**
             * Analyzedat
             * Format: date-time
             */
            analyzedAt: string;
            sourceName: components["schemas"]["SourceName"];
            /** Publishedat */
            publishedAt?: string | null;
            /**
             * Keywords
             * @default []
             */
            keywords: components["schemas"]["KeywordEmbed"][];
            /**
             * Iswatched
             * @default false
             */
            isWatched: boolean;
            original: components["schemas"]["OriginalArticleEmbed"];
        };
        /**
         * NewsFetchRequest
         * @description POST /api/v1/news/fetch request body.
         */
        NewsFetchRequest: {
            /** Sourceids */
            sourceIds?: number[] | null;
        };
        /**
         * NewsFetchResponse
         * @description POST /api/v1/news/fetch response.
         */
        NewsFetchResponse: {
            /** Message */
            message: string;
            /** Sourcescount */
            sourcesCount?: number | null;
            /** Jobid */
            jobId: string;
        };
        /**
         * NewsSourceCreate
         * @description POST /api/v1/sources request body.
         */
        NewsSourceCreate: {
            name: components["schemas"]["SourceName"];
            sourceType: components["schemas"]["SourceType"];
            siteUrl: components["schemas"]["SafeUrl"];
            endpointUrl: components["schemas"]["SafeUrl"];
        };
        /**
         * NewsSourceListResponse
         * @description GET /api/v1/sources response wrapper.
         */
        NewsSourceListResponse: {
            /** Items */
            items: components["schemas"]["NewsSourceResponse"][];
            /** Total */
            total: number;
        };
        /**
         * NewsSourceResponse
         * @description Single news source in API responses.
         */
        NewsSourceResponse: {
            /** Id */
            id: number;
            name: components["schemas"]["SourceName"];
            sourceType: components["schemas"]["SourceType"];
            siteUrl: components["schemas"]["SafeUrl"];
            endpointUrl: components["schemas"]["SafeUrl"];
            /** Isactive */
            isActive: boolean;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /**
         * OriginalArticleEmbed
         * @description 原文記事の参照情報（詳細画面用）
         */
        OriginalArticleEmbed: {
            /** Title */
            title: string;
            url: components["schemas"]["SafeUrl"];
            /** Content */
            content?: string | null;
        };
        /**
         * PaginatedNewsResponse
         * @description Paginated list of news articles.
         */
        PaginatedNewsResponse: {
            /** Items */
            items: components["schemas"]["NewsBrief"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Perpage */
            perPage: number;
            /** Totalpages */
            totalPages: number;
        };
        /**
         * SafeUrl
         * @description HTTP/HTTPS URL validated by Pydantic.
         *
         *     Invariants:
         *     - Uses http or https scheme
         *     - Valid URL structure (scheme + host at minimum)
         *     - 1-2048 characters after trimming
         *     - Immutable after creation
         */
        SafeUrl: string;
        /**
         * SourceName
         * @description Display name for a news source.
         *
         *     Invariants:
         *     - Contains at least one word character
         *     - Only word chars (Unicode), spaces, hyphens, dots
         *     - 1-50 characters after trimming
         *     - Immutable after creation
         */
        SourceName: string;
        /**
         * SourceType
         * @enum {string}
         */
        SourceType: "rss" | "api";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WatchlistCreate
         * @description POST /api/v1/me/watchlist request body.
         */
        WatchlistCreate: {
            /** Newsarticleid */
            newsArticleId: number;
        };
        /**
         * WatchlistListResponse
         * @description GET /api/v1/me/watchlist response wrapper.
         */
        WatchlistListResponse: {
            /** Items */
            items: components["schemas"]["WatchlistResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Perpage */
            perPage: number;
            /** Totalpages */
            totalPages: number;
        };
        /**
         * WatchlistResponse
         * @description Watchlist item in API responses.
         */
        WatchlistResponse: {
            /** Newsarticleid */
            newsArticleId: number;
            /** Originaltitle */
            originalTitle: string;
            /** Originalurl */
            originalUrl: string;
            sourceName: components["schemas"]["SourceName"];
            /** Publishedat */
            publishedAt?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_categories_api_v1_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDetailList"];
                };
            };
        };
    };
    list_keywords_api_v1_keywords_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeywordDetailList"];
                };
            };
        };
    };
    create_keyword_api_v1_keywords_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeywordCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeywordDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_keyword_api_v1_keywords__keyword_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyword_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_keyword_api_v1_keywords__keyword_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyword_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeywordUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeywordDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_watchlist_api_v1_me_watchlist_get: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_to_watchlist_api_v1_me_watchlist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_from_watchlist_api_v1_me_watchlist__news_article_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                news_article_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_news_api_v1_news_get: {
        parameters: {
            query?: {
                keywordId?: number | null;
                kwCategoryId?: number | null;
                sourceId?: number | null;
                impactLevel?: components["schemas"]["ImpactLevel"] | null;
                q?: string | null;
                sortBy?: string;
                sortOrder?: string;
                page?: number;
                perPage?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedNewsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    embed_news_api_v1_news_embed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmbedResponse"];
                };
            };
        };
    };
    get_similar_news_api_v1_news__news_id__similar_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                news_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsBrief"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_news_api_v1_news__news_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                news_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fetch_news_api_v1_news_fetch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["NewsFetchRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsFetchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_api_v1_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsSourceListResponse"];
                };
            };
        };
    };
    create_source_api_v1_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewsSourceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsSourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_api_v1_sources__source_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsSourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_source_api_v1_sources__source_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_source_api_v1_sources__source_id__toggle_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsSourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
