// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { ActivateSourceData, ActivateSourceErrors, ActivateSourceResponses, AddToWatchlistData, AddToWatchlistErrors, AddToWatchlistResponses, CreateNewsSourceData, CreateNewsSourceErrors, CreateNewsSourceResponses, CreateResearchResponseData, CreateResearchResponseErrors, CreateResearchResponseResponses, DeactivateSourceData, DeactivateSourceErrors, DeactivateSourceResponses, DeleteNewsSourceData, DeleteNewsSourceErrors, DeleteNewsSourceResponses, FetchNewsData, FetchNewsErrors, FetchNewsResponses, GetArticleData, GetArticleErrors, GetArticleResponses, GetLatestBriefingData, GetLatestBriefingErrors, GetLatestBriefingResponses, GetPipelineHealthData, GetPipelineHealthErrors, GetPipelineHealthResponses, GetSimilarArticlesData, GetSimilarArticlesErrors, GetSimilarArticlesResponses, GetSourceHealthData, GetSourceHealthErrors, GetSourceHealthResponses, GetTrendsData, GetTrendsErrors, GetTrendsResponses, HealthCheckData, HealthCheckErrors, HealthCheckResponses, ListArticlesData, ListArticlesErrors, ListArticlesInWatchlistData, ListArticlesInWatchlistErrors, ListArticlesInWatchlistResponses, ListArticlesResponses, ListBriefingsData, ListBriefingsErrors, ListBriefingsResponses, ListCategoriesData, ListCategoriesErrors, ListCategoriesResponses, ListNewsSourcesData, ListNewsSourcesErrors, ListNewsSourcesResponses, ListWatchlistIdsData, ListWatchlistIdsErrors, ListWatchlistIdsResponses, RemoveFromWatchlistData, RemoveFromWatchlistErrors, RemoveFromWatchlistResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List Articles
 *
 * 分析済み記事をフィルタとページネーション付きで一覧取得する。
 *
 * レスポンスは user 非依存。per-user の watchlist 状態は
 * GET /api/v1/me/watchlist/ids で別取得し frontend で merge する。
 */
export const listArticles = <ThrowOnError extends boolean = false>(options?: Options<ListArticlesData, ThrowOnError>): RequestResult<ListArticlesResponses, ListArticlesErrors, ThrowOnError> => (options?.client ?? client).get<ListArticlesResponses, ListArticlesErrors, ThrowOnError>({ url: '/api/v1/articles', ...options });

/**
 * pgvector のコサイン距離で意味的に類似した記事を検索する
 *
 * 指定記事に最も類似した記事を返す。
 */
export const getSimilarArticles = <ThrowOnError extends boolean = false>(options: Options<GetSimilarArticlesData, ThrowOnError>): RequestResult<GetSimilarArticlesResponses, GetSimilarArticlesErrors, ThrowOnError> => (options.client ?? client).get<GetSimilarArticlesResponses, GetSimilarArticlesErrors, ThrowOnError>({ url: '/api/v1/articles/{article_id}/similar', ...options });

/**
 * Get Article
 *
 * 単一記事を完全な分析情報付きで取得する。
 */
export const getArticle = <ThrowOnError extends boolean = false>(options: Options<GetArticleData, ThrowOnError>): RequestResult<GetArticleResponses, GetArticleErrors, ThrowOnError> => (options.client ?? client).get<GetArticleResponses, GetArticleErrors, ThrowOnError>({ url: '/api/v1/articles/{article_id}', ...options });

/**
 * List Categories
 *
 * 全カテゴリをネストされたキーワードと記事件数付きで一覧取得する。
 *
 * レスポンスはユーザー非依存。BFF 経由証明を必須とし backend 直叩きを閉じるが、
 * ログイン検証 (login gate) は BFF/Next.js が担うため user は要求しない。
 */
export const listCategories = <ThrowOnError extends boolean = false>(options?: Options<ListCategoriesData, ThrowOnError>): RequestResult<ListCategoriesResponses, ListCategoriesErrors, ThrowOnError> => (options?.client ?? client).get<ListCategoriesResponses, ListCategoriesErrors, ThrowOnError>({ url: '/api/v1/categories', ...options });

/**
 * List Watchlist Ids
 *
 * ウォッチ中の article_id 集合を返す (per-user, cache 不可)。
 */
export const listWatchlistIds = <ThrowOnError extends boolean = false>(options?: Options<ListWatchlistIdsData, ThrowOnError>): RequestResult<ListWatchlistIdsResponses, ListWatchlistIdsErrors, ThrowOnError> => (options?.client ?? client).get<ListWatchlistIdsResponses, ListWatchlistIdsErrors, ThrowOnError>({ url: '/api/v1/me/watchlist/ids', ...options });

/**
 * List Articles In Watchlist
 */
export const listArticlesInWatchlist = <ThrowOnError extends boolean = false>(options?: Options<ListArticlesInWatchlistData, ThrowOnError>): RequestResult<ListArticlesInWatchlistResponses, ListArticlesInWatchlistErrors, ThrowOnError> => (options?.client ?? client).get<ListArticlesInWatchlistResponses, ListArticlesInWatchlistErrors, ThrowOnError>({ url: '/api/v1/me/watchlist', ...options });

/**
 * Add To Watchlist
 */
export const addToWatchlist = <ThrowOnError extends boolean = false>(options: Options<AddToWatchlistData, ThrowOnError>): RequestResult<AddToWatchlistResponses, AddToWatchlistErrors, ThrowOnError> => (options.client ?? client).post<AddToWatchlistResponses, AddToWatchlistErrors, ThrowOnError>({
    url: '/api/v1/me/watchlist',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Remove From Watchlist
 */
export const removeFromWatchlist = <ThrowOnError extends boolean = false>(options: Options<RemoveFromWatchlistData, ThrowOnError>): RequestResult<RemoveFromWatchlistResponses, RemoveFromWatchlistErrors, ThrowOnError> => (options.client ?? client).delete<RemoveFromWatchlistResponses, RemoveFromWatchlistErrors, ThrowOnError>({ url: '/api/v1/me/watchlist/{article_id}', ...options });

/**
 * Get Trends
 *
 * 最新窓の trends snapshot を返す (なければ state="empty")。
 *
 * 保存済み bundle を ``Trends`` schema で再検証する。現行 contract に合わない
 * (旧 shape 等) 場合は ``ValidationError`` が伝播し FastAPI が 500 を返す。
 */
export const getTrends = <ThrowOnError extends boolean = false>(options?: Options<GetTrendsData, ThrowOnError>): RequestResult<GetTrendsResponses, GetTrendsErrors, ThrowOnError> => (options?.client ?? client).get<GetTrendsResponses, GetTrendsErrors, ThrowOnError>({ url: '/api/v1/trends', ...options });

/**
 * List Briefings
 *
 * 全カテゴリの「ある中で最新」briefing を newspaper 一覧用に返す。
 *
 * items は ``Category.id`` 昇順で 11 カテゴリ全部を返す。未生成カテゴリは
 * ``latest=None`` で表現する (frontend で 1 行 ``灰色`` 表示)。
 */
export const listBriefings = <ThrowOnError extends boolean = false>(options?: Options<ListBriefingsData, ThrowOnError>): RequestResult<ListBriefingsResponses, ListBriefingsErrors, ThrowOnError> => (options?.client ?? client).get<ListBriefingsResponses, ListBriefingsErrors, ThrowOnError>({ url: '/api/v1/briefing', ...options });

/**
 * Get Latest Briefing
 *
 * 指定カテゴリの最新 briefing を返す (なければ state="empty")。
 */
export const getLatestBriefing = <ThrowOnError extends boolean = false>(options: Options<GetLatestBriefingData, ThrowOnError>): RequestResult<GetLatestBriefingResponses, GetLatestBriefingErrors, ThrowOnError> => (options.client ?? client).get<GetLatestBriefingResponses, GetLatestBriefingErrors, ThrowOnError>({ url: '/api/v1/briefing/{category_slug}', ...options });

/**
 * Create Research Response
 */
export const createResearchResponse = <ThrowOnError extends boolean = false>(options: Options<CreateResearchResponseData, ThrowOnError>): RequestResult<CreateResearchResponseResponses, CreateResearchResponseErrors, ThrowOnError> => (options.client ?? client).post<CreateResearchResponseResponses, CreateResearchResponseErrors, ThrowOnError>({
    url: '/api/v1/research/responses',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List News Sources
 *
 * 全ニュースソースを一覧取得する。
 */
export const listNewsSources = <ThrowOnError extends boolean = false>(options?: Options<ListNewsSourcesData, ThrowOnError>): RequestResult<ListNewsSourcesResponses, ListNewsSourcesErrors, ThrowOnError> => (options?.client ?? client).get<ListNewsSourcesResponses, ListNewsSourcesErrors, ThrowOnError>({ url: '/api/v1/admin/sources', ...options });

/**
 * Create News Source
 *
 * 新しいニュースソースを作成する。
 */
export const createNewsSource = <ThrowOnError extends boolean = false>(options: Options<CreateNewsSourceData, ThrowOnError>): RequestResult<CreateNewsSourceResponses, CreateNewsSourceErrors, ThrowOnError> => (options.client ?? client).post<CreateNewsSourceResponses, CreateNewsSourceErrors, ThrowOnError>({
    url: '/api/v1/admin/sources',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete News Source
 *
 * ニュースソースを削除する。
 */
export const deleteNewsSource = <ThrowOnError extends boolean = false>(options: Options<DeleteNewsSourceData, ThrowOnError>): RequestResult<DeleteNewsSourceResponses, DeleteNewsSourceErrors, ThrowOnError> => (options.client ?? client).delete<DeleteNewsSourceResponses, DeleteNewsSourceErrors, ThrowOnError>({ url: '/api/v1/admin/sources/{source_id}', ...options });

/**
 * Activate Source
 *
 * ニュースソースを有効化する。
 */
export const activateSource = <ThrowOnError extends boolean = false>(options: Options<ActivateSourceData, ThrowOnError>): RequestResult<ActivateSourceResponses, ActivateSourceErrors, ThrowOnError> => (options.client ?? client).patch<ActivateSourceResponses, ActivateSourceErrors, ThrowOnError>({ url: '/api/v1/admin/sources/{source_id}/activate', ...options });

/**
 * Deactivate Source
 *
 * ニュースソースを無効化する。
 */
export const deactivateSource = <ThrowOnError extends boolean = false>(options: Options<DeactivateSourceData, ThrowOnError>): RequestResult<DeactivateSourceResponses, DeactivateSourceErrors, ThrowOnError> => (options.client ?? client).patch<DeactivateSourceResponses, DeactivateSourceErrors, ThrowOnError>({ url: '/api/v1/admin/sources/{source_id}/deactivate', ...options });

/**
 * Get Source Health
 *
 * 全ニュースソースの取得・分析可能化 health を返す。
 */
export const getSourceHealth = <ThrowOnError extends boolean = false>(options?: Options<GetSourceHealthData, ThrowOnError>): RequestResult<GetSourceHealthResponses, GetSourceHealthErrors, ThrowOnError> => (options?.client ?? client).get<GetSourceHealthResponses, GetSourceHealthErrors, ThrowOnError>({ url: '/api/v1/admin/sources/health', ...options });

/**
 * Fetch News
 *
 * ニュース取得タスクをキュー投入する。
 *
 * source_ids 指定時はソースごとに個別タスクを dispatch、
 * 未指定時は dispatch_sources で全アクティブソースを dispatch。
 */
export const fetchNews = <ThrowOnError extends boolean = false>(options?: Options<FetchNewsData, ThrowOnError>): RequestResult<FetchNewsResponses, FetchNewsErrors, ThrowOnError> => (options?.client ?? client).post<FetchNewsResponses, FetchNewsErrors, ThrowOnError>({
    url: '/api/v1/admin/pipeline/fetch',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Get Pipeline Health
 *
 * パイプライン各 stage の健全性スナップショットを返す。
 */
export const getPipelineHealth = <ThrowOnError extends boolean = false>(options?: Options<GetPipelineHealthData, ThrowOnError>): RequestResult<GetPipelineHealthResponses, GetPipelineHealthErrors, ThrowOnError> => (options?.client ?? client).get<GetPipelineHealthResponses, GetPipelineHealthErrors, ThrowOnError>({ url: '/api/v1/admin/pipeline/health', ...options });

/**
 * Health Check
 */
export const healthCheck = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckData, ThrowOnError>): RequestResult<HealthCheckResponses, HealthCheckErrors, ThrowOnError> => (options?.client ?? client).get<HealthCheckResponses, HealthCheckErrors, ThrowOnError>({ url: '/api/v1/health', ...options });
