// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ActivateSourceData, ActivateSourceErrors, ActivateSourceResponses, AddToWatchlistData, AddToWatchlistErrors, AddToWatchlistResponses, CreateNewsSourceData, CreateNewsSourceErrors, CreateNewsSourceResponses, DeactivateSourceData, DeactivateSourceErrors, DeactivateSourceResponses, DeleteNewsSourceData, DeleteNewsSourceErrors, DeleteNewsSourceResponses, FetchNewsData, FetchNewsErrors, FetchNewsResponses, GetArticleData, GetArticleErrors, GetArticleResponses, GetLatestBriefingData, GetLatestBriefingErrors, GetLatestBriefingResponses, GetSimilarArticlesData, GetSimilarArticlesErrors, GetSimilarArticlesResponses, GetWeeklyTrendsData, GetWeeklyTrendsErrors, GetWeeklyTrendsResponses, HealthCheckData, HealthCheckResponses, ListArticlesData, ListArticlesErrors, ListArticlesInWatchlistData, ListArticlesInWatchlistErrors, ListArticlesInWatchlistResponses, ListArticlesResponses, ListBriefingsData, ListBriefingsErrors, ListBriefingsResponses, ListCategoriesData, ListCategoriesErrors, ListCategoriesResponses, ListNewsSourcesData, ListNewsSourcesErrors, ListNewsSourcesResponses, ListWatchlistIdsData, ListWatchlistIdsErrors, ListWatchlistIdsResponses, RemoveFromWatchlistData, RemoveFromWatchlistErrors, RemoveFromWatchlistResponses, SearchArticlesData, SearchArticlesErrors, SearchArticlesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Search Articles
 *
 * セマンティック類似度で記事を検索する (red-team C1 対策: auth + per-user quota)。
 *
 * 認証済みユーザーごとに 1 日 ``semantic_search_daily_quota_per_user`` 回まで
 * embedding を生成する (Redis atomic counter)。cache hit はクォータを消費しない。
 * anon access は 401、quota 超過は 429。
 *
 * レスポンスは user 非依存。per-user の watchlist 状態は
 * GET /api/v1/me/watchlist/ids で別取得し frontend で merge する。
 */
export const searchArticles = <ThrowOnError extends boolean = false>(options: Options<SearchArticlesData, ThrowOnError>) => (options.client ?? client).get<SearchArticlesResponses, SearchArticlesErrors, ThrowOnError>({ url: '/api/v1/articles/search', ...options });

/**
 * List Articles
 *
 * 分析済み記事をフィルタとページネーション付きで一覧取得する。
 *
 * レスポンスは user 非依存。per-user の watchlist 状態は
 * GET /api/v1/me/watchlist/ids で別取得し frontend で merge する。
 */
export const listArticles = <ThrowOnError extends boolean = false>(options?: Options<ListArticlesData, ThrowOnError>) => (options?.client ?? client).get<ListArticlesResponses, ListArticlesErrors, ThrowOnError>({ url: '/api/v1/articles', ...options });

/**
 * pgvector のコサイン距離で意味的に類似した記事を検索する
 *
 * 指定記事に最も類似した記事を返す。
 */
export const getSimilarArticles = <ThrowOnError extends boolean = false>(options: Options<GetSimilarArticlesData, ThrowOnError>) => (options.client ?? client).get<GetSimilarArticlesResponses, GetSimilarArticlesErrors, ThrowOnError>({ url: '/api/v1/articles/{article_id}/similar', ...options });

/**
 * Get Article
 *
 * 単一記事を完全な分析情報付きで取得する。
 */
export const getArticle = <ThrowOnError extends boolean = false>(options: Options<GetArticleData, ThrowOnError>) => (options.client ?? client).get<GetArticleResponses, GetArticleErrors, ThrowOnError>({ url: '/api/v1/articles/{article_id}', ...options });

/**
 * List Categories
 *
 * 全カテゴリをネストされたキーワードと記事件数付きで一覧取得する。
 *
 * 認証は任意 (BFF プロキシヘッダがあれば検証、無ければ匿名扱い)。
 * レスポンスはユーザー非依存だが、認可境界の一貫性のため検証だけ通す。
 */
export const listCategories = <ThrowOnError extends boolean = false>(options?: Options<ListCategoriesData, ThrowOnError>) => (options?.client ?? client).get<ListCategoriesResponses, ListCategoriesErrors, ThrowOnError>({ url: '/api/v1/categories', ...options });

/**
 * List Watchlist Ids
 *
 * ウォッチ中の article_id 集合を返す (per-user, cache 不可)。
 */
export const listWatchlistIds = <ThrowOnError extends boolean = false>(options?: Options<ListWatchlistIdsData, ThrowOnError>) => (options?.client ?? client).get<ListWatchlistIdsResponses, ListWatchlistIdsErrors, ThrowOnError>({ url: '/api/v1/me/watchlist/ids', ...options });

/**
 * List Articles In Watchlist
 */
export const listArticlesInWatchlist = <ThrowOnError extends boolean = false>(options?: Options<ListArticlesInWatchlistData, ThrowOnError>) => (options?.client ?? client).get<ListArticlesInWatchlistResponses, ListArticlesInWatchlistErrors, ThrowOnError>({ url: '/api/v1/me/watchlist', ...options });

/**
 * Add To Watchlist
 */
export const addToWatchlist = <ThrowOnError extends boolean = false>(options: Options<AddToWatchlistData, ThrowOnError>) => (options.client ?? client).post<AddToWatchlistResponses, AddToWatchlistErrors, ThrowOnError>({
    url: '/api/v1/me/watchlist',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Remove From Watchlist
 */
export const removeFromWatchlist = <ThrowOnError extends boolean = false>(options: Options<RemoveFromWatchlistData, ThrowOnError>) => (options.client ?? client).delete<RemoveFromWatchlistResponses, RemoveFromWatchlistErrors, ThrowOnError>({ url: '/api/v1/me/watchlist/{article_id}', ...options });

/**
 * Get Weekly Trends
 *
 * 最新週の weekly trends snapshot を返す (なければ state="empty")。
 */
export const getWeeklyTrends = <ThrowOnError extends boolean = false>(options?: Options<GetWeeklyTrendsData, ThrowOnError>) => (options?.client ?? client).get<GetWeeklyTrendsResponses, GetWeeklyTrendsErrors, ThrowOnError>({ url: '/api/v1/weekly-trends', ...options });

/**
 * List Briefings
 *
 * 全カテゴリの「ある中で最新」briefing を newspaper 一覧用に返す。
 *
 * items は ``Category.id`` 昇順で 11 カテゴリ全部を返す。未生成カテゴリは
 * ``latest=None`` で表現する (frontend で 1 行 ``灰色`` 表示)。
 */
export const listBriefings = <ThrowOnError extends boolean = false>(options?: Options<ListBriefingsData, ThrowOnError>) => (options?.client ?? client).get<ListBriefingsResponses, ListBriefingsErrors, ThrowOnError>({ url: '/api/v1/briefing', ...options });

/**
 * Get Latest Briefing
 *
 * 指定カテゴリの最新 briefing を返す (なければ state="empty")。
 */
export const getLatestBriefing = <ThrowOnError extends boolean = false>(options: Options<GetLatestBriefingData, ThrowOnError>) => (options.client ?? client).get<GetLatestBriefingResponses, GetLatestBriefingErrors, ThrowOnError>({ url: '/api/v1/briefing/{category_slug}', ...options });

/**
 * List News Sources
 *
 * 全ニュースソースを一覧取得する。
 */
export const listNewsSources = <ThrowOnError extends boolean = false>(options?: Options<ListNewsSourcesData, ThrowOnError>) => (options?.client ?? client).get<ListNewsSourcesResponses, ListNewsSourcesErrors, ThrowOnError>({ url: '/api/v1/admin/sources', ...options });

/**
 * Create News Source
 *
 * 新しいニュースソースを作成する。
 */
export const createNewsSource = <ThrowOnError extends boolean = false>(options: Options<CreateNewsSourceData, ThrowOnError>) => (options.client ?? client).post<CreateNewsSourceResponses, CreateNewsSourceErrors, ThrowOnError>({
    url: '/api/v1/admin/sources',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete News Source
 *
 * ニュースソースを削除する。
 */
export const deleteNewsSource = <ThrowOnError extends boolean = false>(options: Options<DeleteNewsSourceData, ThrowOnError>) => (options.client ?? client).delete<DeleteNewsSourceResponses, DeleteNewsSourceErrors, ThrowOnError>({ url: '/api/v1/admin/sources/{source_id}', ...options });

/**
 * Activate Source
 *
 * ニュースソースを有効化する。
 */
export const activateSource = <ThrowOnError extends boolean = false>(options: Options<ActivateSourceData, ThrowOnError>) => (options.client ?? client).patch<ActivateSourceResponses, ActivateSourceErrors, ThrowOnError>({ url: '/api/v1/admin/sources/{source_id}/activate', ...options });

/**
 * Deactivate Source
 *
 * ニュースソースを無効化する。
 */
export const deactivateSource = <ThrowOnError extends boolean = false>(options: Options<DeactivateSourceData, ThrowOnError>) => (options.client ?? client).patch<DeactivateSourceResponses, DeactivateSourceErrors, ThrowOnError>({ url: '/api/v1/admin/sources/{source_id}/deactivate', ...options });

/**
 * Fetch News
 *
 * ニュース取得タスクをキュー投入する。
 *
 * source_ids 指定時はソースごとに個別タスクを dispatch、
 * 未指定時は dispatch_sources で全アクティブソースを dispatch。
 */
export const fetchNews = <ThrowOnError extends boolean = false>(options?: Options<FetchNewsData, ThrowOnError>) => (options?.client ?? client).post<FetchNewsResponses, FetchNewsErrors, ThrowOnError>({
    url: '/api/v1/admin/pipeline/fetch',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Health Check
 */
export const healthCheck = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckResponses, unknown, ThrowOnError>({ url: '/api/v1/health', ...options });
