// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ArticleBrief
 *
 * GET /api/v1/articles — 一覧カード用
 *
 * per-user の watchlist 状態はこのスキーマには含めない。frontend は
 * GET /api/v1/me/watchlist/ids を別途取得し render 時に Set lookup で
 * merge する (Pattern B)。これにより /articles レスポンスは user 非依存
 * となり HTTP cache/CDN 上で安全に共有できる。
 */
export type ArticleBrief = {
    /**
     * Id
     */
    id: number;
    /**
     * Translatedtitle
     */
    translatedTitle: string;
    /**
     * Summary
     */
    summary: string;
    category: CategoryEmbed;
    source: NewsSourceEmbed;
    /**
     * Publishedat
     */
    publishedAt?: string | null;
};

/**
 * ArticleDetail
 *
 * GET /api/v1/articles/{id} — 詳細画面用
 */
export type ArticleDetail = {
    /**
     * Id
     */
    id: number;
    /**
     * Translatedtitle
     */
    translatedTitle: string;
    /**
     * Summary
     */
    summary: string;
    /**
     * Investortake
     */
    investorTake: string;
    /**
     * Keypoints
     */
    keyPoints?: Array<string>;
    /**
     * Analyzedat
     */
    analyzedAt: string;
    category: CategoryEmbed;
    source: NewsSourceEmbed;
    /**
     * Publishedat
     */
    publishedAt?: string | null;
    original: OriginalArticleEmbed;
};

/**
 * BriefingListItem
 *
 * 一覧 1 行: カテゴリ + 最新 briefing 参照 (未生成は None)。
 */
export type BriefingListItem = {
    category: CategoryOut;
    latest: BriefingListLatest | null;
};

/**
 * BriefingListResponse
 *
 * ``GET /api/v1/briefing`` のレスポンス。
 *
 * ``items`` は ``Category.id`` 昇順で 11 カテゴリ全部を返す。並び順は
 * backend で確定し、frontend での sort を不要にする。
 */
export type BriefingListResponse = {
    /**
     * Currentweekstart
     */
    currentWeekStart: string;
    /**
     * Items
     */
    items: Array<BriefingListItem>;
};

/**
 * CategoryDetail
 *
 * カテゴリ詳細。
 *
 * recentCount は直近 24 時間に AI 分類が完了した記事数。
 */
export type CategoryDetail = {
    slug: CategorySlug;
    name: CategoryName;
    /**
     * Recentcount
     */
    recentCount?: number;
};

/**
 * CategoryDetailList
 *
 * カテゴリ詳細一覧エンドポイント用のラッパー。
 */
export type CategoryDetailList = {
    /**
     * Items
     */
    items: Array<CategoryDetail>;
};

/**
 * CategoryEmbed
 *
 * 記事に紐づくカテゴリの参照情報（カード表示・絞り込み用）。
 *
 * name は表示用、slug は絞り込みキー。id は持たない（表示と絞り込みに不要）。
 * サイドバー用の集計付き CategoryDetail とは役割が異なる。
 */
export type CategoryEmbed = {
    slug: CategorySlug;
    name: CategoryName;
};

/**
 * CategoryName
 *
 * カテゴリの日本語表示名。
 *
 * Invariants:
 * - ワード文字・中黒 (・)・空白・ハイフンで構成
 * - 空文字列や空白のみは不可
 * - 1-50 文字
 * - 生成後は不変
 */
export type CategoryName = string;

/**
 * CategorySlug
 *
 * URL セーフなカテゴリ識別子。
 *
 * Invariants:
 * - 先頭は小文字または数字
 * - 使用可能な文字は小文字・数字・アンダースコアのみ
 * - 1-50 文字
 * - 生成後は不変
 */
export type CategorySlug = string;

/**
 * EmptyBriefing
 *
 * 指定カテゴリに briefing 未生成の状態。
 */
export type EmptyBriefing = {
    /**
     * State
     */
    state?: 'empty';
    category: CategoryOut;
};

/**
 * EmptyWeeklyTrends
 *
 * snapshot 未生成の状態 (窓情報フィールドは存在しない)。
 */
export type EmptyWeeklyTrends = {
    /**
     * State
     */
    state?: 'empty';
};

/**
 * FetchRequest
 *
 * POST /api/v1/admin/pipeline/fetch のリクエストボディ。
 */
export type FetchRequest = {
    /**
     * Sourceids
     */
    sourceIds?: Array<number> | null;
};

/**
 * FetchResponse
 *
 * POST /api/v1/admin/pipeline/fetch のレスポンス。
 */
export type FetchResponse = {
    /**
     * Message
     */
    message: string;
    /**
     * Dispatchedcount
     */
    dispatchedCount?: number | null;
    /**
     * Jobid
     */
    jobId?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MentionName
 *
 * mention の固有名 (週次集計の表示ラベル)。
 *
 * Invariants:
 * - NFKC 正規化 + 前後空白除去 + 連続空白を単一半角空白に統合
 * - 正規化後 1-200 文字
 * - 大文字小文字は保持（"NVIDIA" を表示用にそのまま維持）
 * - 生成後は不変
 *
 * `match_key` プロパティは正規化済み文字列を str.lower() した値を返す。
 * 重複検出・JOIN キーに使う。casefold は使わない (AI 抽出 casing は文脈情報)。
 */
export type MentionName = string;

/**
 * MentionType
 *
 * key_point に登場する固有名の役割 6 軸。
 *
 * タグ単独で役割が読める命名を優先。company / academic / government の
 * 3 軸分割は「投資判断視点で役割が違うものを混ぜると集計信号が薄まる」
 * という設計判断 (spec §Mention type の 6 軸構成 参照)。
 */
export type MentionType = 'company' | 'government' | 'academic' | 'product' | 'technology' | 'person';

/**
 * NewsSourceCreate
 *
 * POST /api/v1/admin/sources のリクエストボディ。
 */
export type NewsSourceCreate = {
    name: SourceName;
    sourceType: SourceType;
    siteUrl: SafeUrl;
    endpointUrl: SafeUrl;
};

/**
 * NewsSourceDetail
 *
 * API レスポンスにおける単一ニュースソース。
 */
export type NewsSourceDetail = {
    /**
     * Id
     */
    id: number;
    name: SourceName;
    sourceType: SourceType;
    siteUrl: SafeUrl;
    endpointUrl: SafeUrl;
    /**
     * Isactive
     */
    isActive: boolean;
    /**
     * Attributionlabel
     */
    attributionLabel?: string | null;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Updatedat
     */
    updatedAt: string;
};

/**
 * NewsSourceDetailList
 *
 * GET /api/v1/admin/sources のレスポンスラッパー。
 */
export type NewsSourceDetailList = {
    /**
     * Items
     */
    items: Array<NewsSourceDetail>;
};

/**
 * NewsSourceEmbed
 *
 * ニュースソースの基本参照情報（フィルタ・表示用）
 */
export type NewsSourceEmbed = {
    name: SourceName;
    /**
     * Attributionlabel
     */
    attributionLabel?: string | null;
};

/**
 * OriginalArticleEmbed
 *
 * 原文記事の参照情報（詳細画面用）
 */
export type OriginalArticleEmbed = {
    /**
     * Title
     */
    title: string;
    url: SafeUrl;
};

/**
 * PaginatedArticleResponse
 *
 * 記事のページネーション付きリスト。
 */
export type PaginatedArticleResponse = {
    /**
     * Items
     */
    items: Array<ArticleBrief>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Perpage
     */
    perPage: number;
    /**
     * Totalpages
     */
    totalPages: number;
};

/**
 * PipelineHealthResponse
 *
 * GET /api/v1/admin/pipeline/health のレスポンス。
 */
export type PipelineHealthResponse = {
    summary: PipelineHealthSummary;
    /**
     * Stages
     */
    stages: Array<PipelineStageHealth>;
};

/**
 * PipelineHealthSummary
 *
 * 全 stage を横断した集計サマリ。
 */
export type PipelineHealthSummary = {
    /**
     * Failedeventcount24H
     */
    failedEventCount24h: number;
    /**
     * Backfilltargettotal
     */
    backfillTargetTotal: number;
    /**
     * Oldestbackfilltargetageseconds
     */
    oldestBackfillTargetAgeSeconds: number | null;
    /**
     * Completionqueuecount
     */
    completionQueueCount: number;
    /**
     * Oldestcompletionqueueageseconds
     */
    oldestCompletionQueueAgeSeconds: number | null;
    /**
     * Observedat
     */
    observedAt: string;
    /**
     * Eventwindowstart
     */
    eventWindowStart: string;
};

/**
 * PipelineStageHealth
 *
 * 1 stage の健全性スナップショット。
 *
 * 全 audit stage を ``Stage`` enum の定義順で返す。queue は completion のみ、
 * backfill は curation/assessment/embedding のみが値を持つ。意味を持たない軸は
 * ``0`` / ``None`` を返す。
 */
export type PipelineStageHealth = {
    stage: Stage;
    /**
     * Succeededeventcount24H
     */
    succeededEventCount24h: number;
    /**
     * Failedeventcount24H
     */
    failedEventCount24h: number;
    /**
     * Queuecount
     */
    queueCount: number;
    /**
     * Oldestqueueageseconds
     */
    oldestQueueAgeSeconds: number | null;
    /**
     * Backfilltargetcount
     */
    backfillTargetCount: number;
    /**
     * Oldestbackfilltargetageseconds
     */
    oldestBackfillTargetAgeSeconds: number | null;
    /**
     * Lastsucceededat
     */
    lastSucceededAt: string | null;
};

/**
 * ReadyBriefing
 *
 * briefing 生成済の状態。
 */
export type ReadyBriefing = {
    /**
     * State
     */
    state?: 'ready';
    /**
     * Weekstart
     */
    weekStart: string;
    /**
     * Generatedat
     */
    generatedAt: string;
    /**
     * Modelname
     */
    modelName: string;
    /**
     * Inputarticlecount
     */
    inputArticleCount: number;
    category: CategoryOut;
    /**
     * Headline
     */
    headline: string;
    /**
     * Overview
     */
    overview: string;
    /**
     * Stories
     */
    stories: Array<StoryOut>;
    /**
     * Articles
     */
    articles: Array<ArticleSummaryOut>;
};

/**
 * ReadyWeeklyTrends
 *
 * snapshot 生成済の状態。
 */
export type ReadyWeeklyTrends = {
    /**
     * State
     */
    state?: 'ready';
    /**
     * Windowstart
     */
    windowStart: string;
    /**
     * Windowend
     */
    windowEnd: string;
    /**
     * Generatedat
     */
    generatedAt: string;
    /**
     * Sourceanalysiscount
     */
    sourceAnalysisCount: number;
    /**
     * Categories
     */
    categories: Array<CategoryTrendsOut>;
};

/**
 * SafeUrl
 *
 * Pydantic によって検証された HTTP/HTTPS URL。
 *
 * Invariants:
 * - http または https スキームを使用
 * - 有効な URL 構造 (最低でも scheme + host)
 * - ホストが IP リテラルなら ``PublicIpAddress`` として valid
 * (例: ``http://169.254.169.254/`` は拒否)
 * - トリム後 1-2048 文字
 * - 生成後は不変
 */
export type SafeUrl = string;

/**
 * SortOrder
 */
export type SortOrder = 'asc' | 'desc';

/**
 * SourceName
 *
 * ニュースソースの表示名。
 *
 * Invariants:
 * - 少なくとも 1 つのワード文字を含む
 * - 使用可能文字は Unicode ワード文字・空白・ハイフン・ドット
 * - トリム後 1-50 文字
 * - 生成後は不変
 */
export type SourceName = string;

/**
 * SourceType
 */
export type SourceType = 'rss' | 'api' | 'html';

/**
 * Stage
 *
 * パイプラインの 11 Stage。
 *
 * BRIEFING は週次 LLM ブリーフィング生成 (``app/insights/briefing/``)。
 * TREND_DISCOVERY は rolling 7d の trend discovery run
 * (``app/insights/trend_discovery/``)。
 */
export type Stage = 'dispatch' | 'acquisition' | 'completion' | 'curation' | 'assessment' | 'embedding' | 'backfill_curate' | 'backfill_assess' | 'backfill_embed' | 'briefing' | 'trend_discovery';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WatchlistCreate
 *
 * POST /api/v1/me/watchlist のリクエストボディ。
 */
export type WatchlistCreate = {
    /**
     * Articleid
     */
    articleId: number;
};

/**
 * WatchlistIds
 *
 * GET /api/v1/me/watchlist/ids のレスポンス。
 *
 * 記事リソースから per-user フラグを切り離し、frontend が render 時に
 * Set lookup で merge するための per-user メンバーシップ ID 集合。
 */
export type WatchlistIds = {
    /**
     * Ids
     */
    ids: Array<number>;
};

/**
 * _ArticleSummaryOut
 *
 * ``stories[].articleIds`` から参照される記事のサマリ。
 */
export type ArticleSummaryOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Titleja
     */
    titleJa: string;
    /**
     * Sourcename
     */
    sourceName: string;
    /**
     * Url
     */
    url: string;
};

/**
 * _BriefingListLatest
 *
 * 一覧行に同梱する「最新 briefing 参照」。
 *
 * 未生成カテゴリでは ``BriefingListItem.latest = None`` で表現する。
 * 詳細 (``ReadyBriefing``) と異なり overview / stories 等は持たず、
 * 一覧で表示する短い見出しのみ。
 */
export type BriefingListLatest = {
    /**
     * Weekstart
     */
    weekStart: string;
    /**
     * Headline
     */
    headline: string;
};

/**
 * _CategoryOut
 */
export type CategoryOut = {
    /**
     * Id
     */
    id: number;
    slug: CategorySlug;
    name: CategoryName;
};

/**
 * _CategoryTrendsOut
 */
export type CategoryTrendsOut = {
    /**
     * Categoryid
     */
    categoryId: number;
    categorySlug: CategorySlug;
    categoryName: CategoryName;
    /**
     * Trendingentities
     */
    trendingEntities: Array<EntityTrendOut>;
    /**
     * Newentities
     */
    newEntities: Array<NewEntityOut>;
};

/**
 * _EntityTrendOut
 */
export type EntityTrendOut = {
    name: MentionName;
    type: MentionType;
    /**
     * Currentcount
     */
    currentCount: number;
    /**
     * Previouscount
     */
    previousCount: number;
    /**
     * Hotnessscore
     */
    hotnessScore: number;
};

/**
 * _NewEntityOut
 */
export type NewEntityOut = {
    name: MentionName;
    type: MentionType;
    /**
     * Currentcount
     */
    currentCount: number;
};

/**
 * _StoryOut
 */
export type StoryOut = {
    /**
     * Takeaway
     */
    takeaway: string;
    /**
     * Articleids
     */
    articleIds: Array<number>;
};

export type ListArticlesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Perpage
         */
        perPage?: number;
        /**
         * Category
         *
         * Outbound primary filter key. Accepts a category slug.
         */
        category?: CategorySlug | null;
        sortOrder?: SortOrder;
    };
    url: '/api/v1/articles';
};

export type ListArticlesErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListArticlesError = ListArticlesErrors[keyof ListArticlesErrors];

export type ListArticlesResponses = {
    /**
     * Successful Response
     */
    200: PaginatedArticleResponse;
};

export type ListArticlesResponse = ListArticlesResponses[keyof ListArticlesResponses];

export type GetSimilarArticlesData = {
    body?: never;
    path: {
        /**
         * Article Id
         */
        article_id: number;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/articles/{article_id}/similar';
};

export type GetSimilarArticlesErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * News article not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSimilarArticlesError = GetSimilarArticlesErrors[keyof GetSimilarArticlesErrors];

export type GetSimilarArticlesResponses = {
    /**
     * Response Get Similar Articles Api V1 Articles  Article Id  Similar Get
     *
     * Successful Response
     */
    200: Array<ArticleBrief>;
};

export type GetSimilarArticlesResponse = GetSimilarArticlesResponses[keyof GetSimilarArticlesResponses];

export type GetArticleData = {
    body?: never;
    path: {
        /**
         * Article Id
         */
        article_id: number;
    };
    query?: never;
    url: '/api/v1/articles/{article_id}';
};

export type GetArticleErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * News article not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetArticleError = GetArticleErrors[keyof GetArticleErrors];

export type GetArticleResponses = {
    /**
     * Successful Response
     */
    200: ArticleDetail;
};

export type GetArticleResponse = GetArticleResponses[keyof GetArticleResponses];

export type ListCategoriesData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/categories';
};

export type ListCategoriesErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListCategoriesError = ListCategoriesErrors[keyof ListCategoriesErrors];

export type ListCategoriesResponses = {
    /**
     * Successful Response
     */
    200: CategoryDetailList;
};

export type ListCategoriesResponse = ListCategoriesResponses[keyof ListCategoriesResponses];

export type ListWatchlistIdsData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/me/watchlist/ids';
};

export type ListWatchlistIdsErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListWatchlistIdsError = ListWatchlistIdsErrors[keyof ListWatchlistIdsErrors];

export type ListWatchlistIdsResponses = {
    /**
     * Successful Response
     */
    200: WatchlistIds;
};

export type ListWatchlistIdsResponse = ListWatchlistIdsResponses[keyof ListWatchlistIdsResponses];

export type ListArticlesInWatchlistData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Perpage
         */
        perPage?: number;
    };
    url: '/api/v1/me/watchlist';
};

export type ListArticlesInWatchlistErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListArticlesInWatchlistError = ListArticlesInWatchlistErrors[keyof ListArticlesInWatchlistErrors];

export type ListArticlesInWatchlistResponses = {
    /**
     * Successful Response
     */
    200: PaginatedArticleResponse;
};

export type ListArticlesInWatchlistResponse = ListArticlesInWatchlistResponses[keyof ListArticlesInWatchlistResponses];

export type AddToWatchlistData = {
    body: WatchlistCreate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/me/watchlist';
};

export type AddToWatchlistErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * News article not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddToWatchlistError = AddToWatchlistErrors[keyof AddToWatchlistErrors];

export type AddToWatchlistResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type RemoveFromWatchlistData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Article Id
         */
        article_id: number;
    };
    query?: never;
    url: '/api/v1/me/watchlist/{article_id}';
};

export type RemoveFromWatchlistErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Watchlist item not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveFromWatchlistError = RemoveFromWatchlistErrors[keyof RemoveFromWatchlistErrors];

export type RemoveFromWatchlistResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RemoveFromWatchlistResponse = RemoveFromWatchlistResponses[keyof RemoveFromWatchlistResponses];

export type GetWeeklyTrendsData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/weekly-trends';
};

export type GetWeeklyTrendsErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWeeklyTrendsError = GetWeeklyTrendsErrors[keyof GetWeeklyTrendsErrors];

export type GetWeeklyTrendsResponses = {
    /**
     * Response Get Weekly Trends Api V1 Weekly Trends Get
     *
     * Successful Response
     */
    200: ({
        state: 'ready';
    } & ReadyWeeklyTrends) | ({
        state: 'empty';
    } & EmptyWeeklyTrends);
};

export type GetWeeklyTrendsResponse = GetWeeklyTrendsResponses[keyof GetWeeklyTrendsResponses];

export type ListBriefingsData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/briefing';
};

export type ListBriefingsErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListBriefingsError = ListBriefingsErrors[keyof ListBriefingsErrors];

export type ListBriefingsResponses = {
    /**
     * Successful Response
     */
    200: BriefingListResponse;
};

export type ListBriefingsResponse = ListBriefingsResponses[keyof ListBriefingsResponses];

export type GetLatestBriefingData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Category Slug
         */
        category_slug: string;
    };
    query?: never;
    url: '/api/v1/briefing/{category_slug}';
};

export type GetLatestBriefingErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * category not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLatestBriefingError = GetLatestBriefingErrors[keyof GetLatestBriefingErrors];

export type GetLatestBriefingResponses = {
    /**
     * Response Get Latest Briefing Api V1 Briefing  Category Slug  Get
     *
     * Successful Response
     */
    200: ({
        state: 'ready';
    } & ReadyBriefing) | ({
        state: 'empty';
    } & EmptyBriefing);
};

export type GetLatestBriefingResponse = GetLatestBriefingResponses[keyof GetLatestBriefingResponses];

export type ListNewsSourcesData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/admin/sources';
};

export type ListNewsSourcesErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListNewsSourcesError = ListNewsSourcesErrors[keyof ListNewsSourcesErrors];

export type ListNewsSourcesResponses = {
    /**
     * Successful Response
     */
    200: NewsSourceDetailList;
};

export type ListNewsSourcesResponse = ListNewsSourcesResponses[keyof ListNewsSourcesResponses];

export type CreateNewsSourceData = {
    body: NewsSourceCreate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/admin/sources';
};

export type CreateNewsSourceErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateNewsSourceError = CreateNewsSourceErrors[keyof CreateNewsSourceErrors];

export type CreateNewsSourceResponses = {
    /**
     * Successful Response
     */
    201: NewsSourceDetail;
};

export type CreateNewsSourceResponse = CreateNewsSourceResponses[keyof CreateNewsSourceResponses];

export type DeleteNewsSourceData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Source Id
         */
        source_id: number;
    };
    query?: never;
    url: '/api/v1/admin/sources/{source_id}';
};

export type DeleteNewsSourceErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * News source not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteNewsSourceError = DeleteNewsSourceErrors[keyof DeleteNewsSourceErrors];

export type DeleteNewsSourceResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteNewsSourceResponse = DeleteNewsSourceResponses[keyof DeleteNewsSourceResponses];

export type ActivateSourceData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Source Id
         */
        source_id: number;
    };
    query?: never;
    url: '/api/v1/admin/sources/{source_id}/activate';
};

export type ActivateSourceErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * News source not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ActivateSourceError = ActivateSourceErrors[keyof ActivateSourceErrors];

export type ActivateSourceResponses = {
    /**
     * Successful Response
     */
    200: NewsSourceDetail;
};

export type ActivateSourceResponse = ActivateSourceResponses[keyof ActivateSourceResponses];

export type DeactivateSourceData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Source Id
         */
        source_id: number;
    };
    query?: never;
    url: '/api/v1/admin/sources/{source_id}/deactivate';
};

export type DeactivateSourceErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * News source not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeactivateSourceError = DeactivateSourceErrors[keyof DeactivateSourceErrors];

export type DeactivateSourceResponses = {
    /**
     * Successful Response
     */
    200: NewsSourceDetail;
};

export type DeactivateSourceResponse = DeactivateSourceResponses[keyof DeactivateSourceResponses];

export type FetchNewsData = {
    /**
     * Body
     */
    body?: FetchRequest | null;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/admin/pipeline/fetch';
};

export type FetchNewsErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FetchNewsError = FetchNewsErrors[keyof FetchNewsErrors];

export type FetchNewsResponses = {
    /**
     * Successful Response
     */
    202: FetchResponse;
};

export type FetchNewsResponse = FetchNewsResponses[keyof FetchNewsResponses];

export type GetPipelineHealthData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/admin/pipeline/health';
};

export type GetPipelineHealthErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPipelineHealthError = GetPipelineHealthErrors[keyof GetPipelineHealthErrors];

export type GetPipelineHealthResponses = {
    /**
     * Successful Response
     */
    200: PipelineHealthResponse;
};

export type GetPipelineHealthResponse = GetPipelineHealthResponses[keyof GetPipelineHealthResponses];

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type HealthCheckErrors = {
    /**
     * Bad request
     */
    400: unknown;
};

export type HealthCheckResponses = {
    /**
     * Response Health Check Api V1 Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];
