"""add content fields to news_articles

Revision ID: 3a9bf03a0b5f
Revises: dc3cc7a3c587
Create Date: 2026-02-20 09:48:15.770816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3a9bf03a0b5f'
down_revision: Union[str, None] = 'dc3cc7a3c587'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_articles', sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('news_articles', sa.Column('content_fetched_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_articles', 'content_fetched_at')
    op.drop_column('news_articles', 'content')
    # ### end Alembic commands ###
