"""create initial tables

Revision ID: b751d5bc7311
Revises:
Create Date: 2026-02-16 06:25:14.837722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b751d5bc7311'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword')
    )
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_original', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('description_original', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_news_fetched', 'news_articles', ['fetched_at'], unique=False, postgresql_using='btree')
    op.create_index('idx_news_published', 'news_articles', ['published_at'], unique=False, postgresql_using='btree')
    op.create_index(op.f('ix_news_articles_url'), 'news_articles', ['url'], unique=True)
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_article_id', sa.Integer(), nullable=False),
    sa.Column('title_ja', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('summary_ja', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sentiment', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('impact_score', sa.Integer(), nullable=False),
    sa.Column('key_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reasoning', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_provider', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('ai_model', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['news_article_id'], ['news_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_article_id')
    )
    op.create_index('idx_analyses_impact', 'analyses', ['impact_score'], unique=False)
    op.create_index('idx_analyses_sentiment', 'analyses', ['sentiment'], unique=False)
    op.create_table('news_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_article_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['news_article_id'], ['news_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_article_id', 'keyword_id', name='uq_news_keyword')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_keywords')
    op.drop_index('idx_analyses_sentiment', table_name='analyses')
    op.drop_index('idx_analyses_impact', table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_news_articles_url'), table_name='news_articles')
    op.drop_index('idx_news_published', table_name='news_articles', postgresql_using='btree')
    op.drop_index('idx_news_fetched', table_name='news_articles', postgresql_using='btree')
    op.drop_table('news_articles')
    op.drop_table('keywords')
    # ### end Alembic commands ###
