"""External search package。公開名は package root から import する。"""

from app.agent.evidence_collection.external_search.contract import (
    EVIDENCE_CLAIM_MAX_CHARS,
    EVIDENCE_WHY_SELECTED_MAX_CHARS,
    EXTERNAL_CONTENT_MAX_CHARS,
    EXTERNAL_QUERY_MAX_CHARS,
    EXTERNAL_SEARCH_AGENT_HARD_LIMIT,
    EXTERNAL_SEARCH_HIT_POOL_LIMIT_PER_TASK,
    EXTERNAL_SEARCH_HITS_PER_QUERY,
    EXTERNAL_SEARCH_TOOL_NAME,
    EXTERNAL_TASK_QUERY_LIMIT,
    MISSING_ITEM_MAX_CHARS,
    ExternalQueryDraft,
    ExternalQueryGenerationInput,
    ExternalResearchRuntime,
    ExternalResearchRuntimeFactory,
    ExternalSearchDateFilter,
    ExternalSearchHit,
    ExternalSearchProviderError,
    ExternalSearchTool,
    ExternalSearchToolFailureReason,
    ExternalSearchToolInput,
    ExternalSearchToolName,
    TimeFilterFailureReason,
)
from app.agent.evidence_collection.external_search.policy import (
    PROVIDER_SEARCH_TIMEOUT_SECONDS,
    QUERY_GENERATE_TIMEOUT_SECONDS,
    resolve_external_search_agent_count,
)
from app.agent.evidence_collection.external_search.tavily import (
    TAVILY_MAX_RESULTS_LIMIT,
    TAVILY_REQUEST_TIMEOUT_SECONDS,
    TAVILY_SEARCH_URL,
    TavilyExternalSearchTool,
)
from app.agent.evidence_collection.external_search.time_filter import (
    ExternalSearchDateFilterResolutionError,
    resolve_external_search_date_filter,
)

__all__ = [
    "EVIDENCE_CLAIM_MAX_CHARS",
    "EVIDENCE_WHY_SELECTED_MAX_CHARS",
    "EXTERNAL_CONTENT_MAX_CHARS",
    "EXTERNAL_QUERY_MAX_CHARS",
    "EXTERNAL_SEARCH_AGENT_HARD_LIMIT",
    "EXTERNAL_SEARCH_HITS_PER_QUERY",
    "EXTERNAL_SEARCH_HIT_POOL_LIMIT_PER_TASK",
    "EXTERNAL_SEARCH_TOOL_NAME",
    "EXTERNAL_TASK_QUERY_LIMIT",
    "ExternalQueryDraft",
    "ExternalQueryGenerationInput",
    "ExternalSearchHit",
    "ExternalSearchDateFilter",
    "ExternalSearchProviderError",
    "ExternalResearchRuntime",
    "ExternalResearchRuntimeFactory",
    "ExternalSearchTool",
    "ExternalSearchToolFailureReason",
    "ExternalSearchToolInput",
    "ExternalSearchToolName",
    "MISSING_ITEM_MAX_CHARS",
    "PROVIDER_SEARCH_TIMEOUT_SECONDS",
    "QUERY_GENERATE_TIMEOUT_SECONDS",
    "TAVILY_MAX_RESULTS_LIMIT",
    "TAVILY_REQUEST_TIMEOUT_SECONDS",
    "TAVILY_SEARCH_URL",
    "TavilyExternalSearchTool",
    "TimeFilterFailureReason",
    "ExternalSearchDateFilterResolutionError",
    "resolve_external_search_date_filter",
    "resolve_external_search_agent_count",
]
