"""External search package。公開名は package root から import する。"""

from app.agent.evidence_collection.external_search.contract import (
    CANDIDATE_SNIPPET_MAX_CHARS,
    EVIDENCE_CLAIM_MAX_CHARS,
    EVIDENCE_WHY_SELECTED_MAX_CHARS,
    EXTERNAL_QUERY_MAX_CHARS,
    EXTERNAL_SEARCH_AGENT_HARD_LIMIT,
    EXTERNAL_SEARCH_CANDIDATE_POOL_LIMIT_PER_TASK,
    EXTERNAL_SEARCH_CANDIDATES_PER_QUERY,
    EXTERNAL_SEARCH_EVIDENCE_LIMIT_PER_TASK,
    EXTERNAL_SEARCH_MISSING_LIMIT_PER_TASK,
    EXTERNAL_TASK_QUERY_LIMIT,
    MISSING_ITEM_MAX_CHARS,
    EvidenceSelection,
    EvidenceSelectionResult,
    EvidenceSelector,
    ExternalEvidenceSelectorError,
    ExternalQueryGenerationError,
    ExternalSearchCandidate,
    ExternalSearchEvidence,
    ExternalSearchOutcome,
    ExternalSearchProviderError,
    ExternalSearchRequest,
    ExternalSearchRunner,
    ExternalSearchRunResult,
    QueryGenerator,
    ResearchTaskReport,
    ResearchTaskStatus,
    SearchProvider,
)
from app.agent.evidence_collection.external_search.runner import (
    EVIDENCE_SELECT_TIMEOUT_SECONDS,
    PROVIDER_SEARCH_TIMEOUT_SECONDS,
    QUERY_GENERATE_TIMEOUT_SECONDS,
    ExternalSearchResearchRunner,
)
from app.agent.evidence_collection.external_search.service import (
    ExternalSearchService,
    resolve_external_search_agent_count,
)
from app.agent.evidence_collection.external_search.tavily import (
    TAVILY_MAX_RESULTS_LIMIT,
    TAVILY_REQUEST_TIMEOUT_SECONDS,
    TAVILY_SEARCH_URL,
    TavilySearchProvider,
)

__all__ = [
    "CANDIDATE_SNIPPET_MAX_CHARS",
    "EVIDENCE_CLAIM_MAX_CHARS",
    "EVIDENCE_SELECT_TIMEOUT_SECONDS",
    "EVIDENCE_WHY_SELECTED_MAX_CHARS",
    "EXTERNAL_QUERY_MAX_CHARS",
    "EXTERNAL_SEARCH_AGENT_HARD_LIMIT",
    "EXTERNAL_SEARCH_CANDIDATES_PER_QUERY",
    "EXTERNAL_SEARCH_CANDIDATE_POOL_LIMIT_PER_TASK",
    "EXTERNAL_SEARCH_EVIDENCE_LIMIT_PER_TASK",
    "EXTERNAL_SEARCH_MISSING_LIMIT_PER_TASK",
    "EXTERNAL_TASK_QUERY_LIMIT",
    "EvidenceSelection",
    "EvidenceSelectionResult",
    "EvidenceSelector",
    "ExternalEvidenceSelectorError",
    "ExternalQueryGenerationError",
    "ExternalSearchCandidate",
    "ExternalSearchEvidence",
    "ExternalSearchOutcome",
    "ExternalSearchProviderError",
    "ExternalSearchRequest",
    "ExternalSearchResearchRunner",
    "ExternalSearchRunResult",
    "ExternalSearchRunner",
    "ExternalSearchService",
    "MISSING_ITEM_MAX_CHARS",
    "PROVIDER_SEARCH_TIMEOUT_SECONDS",
    "QUERY_GENERATE_TIMEOUT_SECONDS",
    "QueryGenerator",
    "ResearchTaskReport",
    "ResearchTaskStatus",
    "SearchProvider",
    "TAVILY_MAX_RESULTS_LIMIT",
    "TAVILY_REQUEST_TIMEOUT_SECONDS",
    "TAVILY_SEARCH_URL",
    "TavilySearchProvider",
    "resolve_external_search_agent_count",
]
